/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Me: () => import('#controllers/me_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  Tasks: () => import('#controllers/tasks_controller'),
  Users: () => import('#controllers/users_controller'),
}
